website:
  title: "Nat's Super Sexy Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/nathalie-pare
      - icon: github
        href: https://github.com/natpare/NatsSuperSexyWebsite.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Nathalie Pare"

format:
  html:
    theme: sandstone
    toc: true

editor: source

